-- MySQL Script generated by MySQL Workbench
-- Fri Apr 13 16:21:41 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema financas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema financas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `financas` DEFAULT CHARACTER SET utf8 ;
USE `financas` ;

-- -----------------------------------------------------
-- Table `financas`.`dinheiro_recebido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financas`.`dinheiro_recebido` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `fonte_recebimento` ENUM('S', 'O') CHARACTER SET 'big5' NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `financas`.`saldo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financas`.`saldo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `saldo` INT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = hebrew;


-- -----------------------------------------------------
-- Table `financas`.`compras_avista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financas`.`compras_avista` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `valor` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `financas`.`cartao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financas`.`cartao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `saldo` VARCHAR(45) NULL,
  `data_vencimento` DATE NOT NULL,
  `data_fechamento` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `financas`.`compras_parceladas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financas`.`compras_parceladas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `data` DATE NOT NULL,
  `quant_parcelas` INT NOT NULL,
  `pago` ENUM('Y', 'N') NOT NULL DEFAULT 'N',
  `cartao_id` INT NOT NULL,
  PRIMARY KEY (`id`, `cartao_id`),
  INDEX `fk_compras_parceladas_cartao_idx` (`cartao_id` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `financas`.`parcelas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financas`.`parcelas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pago` ENUM('Y', 'N') NOT NULL DEFAULT 'N',
  `compras_parceladas_id` INT NOT NULL,
  `compras_parceladas_cartao_id` INT NOT NULL,
  PRIMARY KEY (`id`, `compras_parceladas_id`, `compras_parceladas_cartao_id`),
  INDEX `fk_parcelas_compras_parceladas1_idx` (`compras_parceladas_id` ASC, `compras_parceladas_cartao_id` ASC))
ENGINE = MyISAM;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
